export const AUTHENTICATED = 'AUTHENTICATED';

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const ADD_USER_LIST = 'ADD_USER_LIST';
export const SET_LIST_USERS = 'SET_LIST_USERS';

export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_FINISHED = 'REQUEST_FINISHED';

export const CREATE_POST = 'CREATE_POST';

export const SET_CHANNEL = 'SET_CHANNEL';

export const HAS_NOTIFICATION_CHAT = 'HAS_NOTIFICATION_CHAT';

export const SET_LIST_USER_BLOCKS = 'SET_LIST_USER_BLOCKS';
export const SET_LIST_USER_WHO_BLOCKS_CURRENT_USER = 'SET_LIST_USER_WHO_BLOCKS_CURRENT_USER';

export const AGREE_TERM = 'AGREE_TERM';
export const READ_TUTORIAL = 'READ_TUTORIAL';
export const GREETING_POST = 'GREETING_POST';

export const SET_CHANGWATS = 'SET_CHANGWAT';
export const SET_AMPHOES = 'SET_AMPHOES';
export const SET_TAMBONS = 'SET_TAMBONS';
